[package]
name = "aloroid/fusionplasma"
description = "Allows for wrapping Fusion components into Plasma widgets."
license = "MIT"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Plasma = "aloroid/plasma@0.4.4"