[package]
name = "aloroid/fusionplasma"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Plasma = "aloroid/plasma@0.4.4"